@startuml
set separator none
title Identity Service - Containers

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Container>

System(3rdPartyApplication, "3rd-Party Application", $descr="A system to use PassGuard as a identity provider", $tags="", $link="")

System_Boundary("IdentityService_boundary", "Identity Service", $tags="") {
  Container(IdentityService.LoginWebApplication, "Login Web Application", $techn="NextJS", $descr="Authenticator(Client Device)", $tags="", $link="")
  Container(IdentityService.PassGuardServerApplication, "PassGuard Server Application", $techn="NestJS", $descr="API server", $tags="", $link="")
  ContainerDb(IdentityService.Database, "Database", $techn="MySQL", $descr="Stores identification related data to athenticate", $tags="", $link="")
}

Rel(3rdPartyApplication, IdentityService.LoginWebApplication, "", $techn="", $tags="", $link="")
Rel(IdentityService.LoginWebApplication, IdentityService.PassGuardServerApplication, "", $techn="", $tags="", $link="")
Rel(IdentityService.LoginWebApplication, IdentityService.LoginWebApplication, "", $techn="", $tags="", $link="")
Rel(IdentityService.PassGuardServerApplication, IdentityService.Database, "", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
@enduml