@startuml
set separator none
title Identity Solution - Containers

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Container>

System(3rdPartyApplication, "3rd-Party Application", $descr="A system to use PassGuard as a identity provider", $tags="", $link="")

System_Boundary("IdentitySolution_boundary", "Identity Solution", $tags="") {
  Container(IdentitySolution.LoginWebApplication, "Login Web Application", $techn="NextJS", $descr="Authenticator(Client Device)", $tags="", $link="")
  Container(IdentitySolution.PassGuardServerApplication, "PassGuard Server Application", $techn="NestJS", $descr="API server", $tags="", $link="")
  ContainerDb(IdentitySolution.Database, "Database", $techn="MySQL", $descr="Stores identification related data to athenticate", $tags="", $link="")
}

Rel(IdentitySolution.PassGuardServerApplication, IdentitySolution.Database, "", $techn="", $tags="", $link="")
Rel(3rdPartyApplication, IdentitySolution.LoginWebApplication, "", $techn="", $tags="", $link="")
Rel(IdentitySolution.LoginWebApplication, IdentitySolution.PassGuardServerApplication, "", $techn="", $tags="", $link="")
Rel(IdentitySolution.LoginWebApplication, IdentitySolution.LoginWebApplication, "", $techn="", $tags="", $link="")
Rel(3rdPartyApplication, IdentitySolution.PassGuardServerApplication, "", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
@enduml