@startuml
set separator none
title Identity Solution - PassGuard Server Application - Components

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Container>
!include <C4/C4_Component>

Container(IdentitySolution.LoginWebApplication, "Login Web Application", $techn="NextJS", $descr="Authenticator(Client Device)", $tags="", $link="")
ContainerDb(IdentitySolution.Database, "Database", $techn="MySQL", $descr="Stores identification related data to athenticate", $tags="", $link="")

Container_Boundary("IdentitySolution.PassGuardServerApplication_boundary", "PassGuard Server Application", $tags="") {
  AddBoundaryTag("Application Layer", $borderColor="#cccccc", $fontColor="#cccccc", $borderStyle="Dashed", $borderThickness="1")
  Boundary(group_1, "Application Layer", $tags="Application Layer") {
    WithoutPropertyHeader()
    AddProperty("Layer","Application")
    Component(IdentitySolution.PassGuardServerApplication.LoginService, "Login Service", $techn="NextJS Service", $descr="", $tags="", $link="")
  }

  AddBoundaryTag("Business Logic Layer", $borderColor="#cccccc", $fontColor="#cccccc", $borderStyle="Dashed", $borderThickness="1")
  Boundary(group_2, "Business Logic Layer", $tags="Business Logic Layer") {
    WithoutPropertyHeader()
    AddProperty("Layer","Business Logic")
    Component(IdentitySolution.PassGuardServerApplication.AuthenticationService, "Authentication Service", $techn="NextJS Service", $descr="Business Logic: Authentication Service", $tags="", $link="")
    WithoutPropertyHeader()
    AddProperty("Layer","Business Logic")
    Component(IdentitySolution.PassGuardServerApplication.AuthorizationService, "Authorization Service", $techn="NextJS Service", $descr="Business Logic: Authorization Service", $tags="", $link="")
  }

  AddBoundaryTag("Infrastructure Layer", $borderColor="#cccccc", $fontColor="#cccccc", $borderStyle="Dashed", $borderThickness="1")
  Boundary(group_3, "Infrastructure Layer", $tags="Infrastructure Layer") {
    WithoutPropertyHeader()
    AddProperty("Layer","Infrastructure")
    Component(IdentitySolution.PassGuardServerApplication.GeneralRepository, "General Repository", $techn="prisma", $descr="Business Logic: Authentication Service", $tags="", $link="")
  }

}

Rel(IdentitySolution.LoginWebApplication, IdentitySolution.LoginWebApplication, "", $techn="", $tags="", $link="")
Rel(IdentitySolution.PassGuardServerApplication.LoginService, IdentitySolution.PassGuardServerApplication.AuthenticationService, "", $techn="", $tags="", $link="")
Rel(IdentitySolution.PassGuardServerApplication.AuthenticationService, IdentitySolution.PassGuardServerApplication.GeneralRepository, "", $techn="", $tags="", $link="")
Rel(IdentitySolution.LoginWebApplication, IdentitySolution.PassGuardServerApplication.LoginService, "", $techn="", $tags="", $link="")
Rel(IdentitySolution.PassGuardServerApplication.GeneralRepository, IdentitySolution.Database, "", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
@enduml