@startuml
set separator none
title Identity Solution - PassGuard Server Application - Components

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Container>
!include <C4/C4_Component>

System(3rdPartyApplication, "3rd-Party Application", $descr="A system to use PassGuard as a identity provider", $tags="", $link="")
ContainerDb(IdentitySolution.Database, "Database", $techn="MySQL", $descr="Stores identification related data to athenticate", $tags="", $link="")

Container_Boundary("IdentitySolution.PassGuardServerApplication_boundary", "PassGuard Server Application", $tags="") {
  Component(IdentitySolution.PassGuardServerApplication.credentialModule, "credentialModule", $techn="NextJS Module", $descr="credential module", $tags="", $link="")
  Component(IdentitySolution.PassGuardServerApplication.serviceModule, "serviceModule", $techn="NextJS Module", $descr="service module", $tags="", $link="")
  Component(IdentitySolution.PassGuardServerApplication.userModule, "userModule", $techn="NextJS Module", $descr="user module", $tags="", $link="")
}

Rel(3rdPartyApplication, IdentitySolution.PassGuardServerApplication.serviceModule, "", $techn="", $tags="", $link="")
Rel(3rdPartyApplication, IdentitySolution.PassGuardServerApplication.credentialModule, "", $techn="", $tags="", $link="")
Rel(IdentitySolution.PassGuardServerApplication.credentialModule, IdentitySolution.PassGuardServerApplication.serviceModule, "", $techn="", $tags="", $link="")
Rel(IdentitySolution.PassGuardServerApplication.serviceModule, IdentitySolution.PassGuardServerApplication.userModule, "", $techn="", $tags="", $link="")
Rel(IdentitySolution.PassGuardServerApplication.userModule, IdentitySolution.Database, "", $techn="", $tags="", $link="")
Rel(IdentitySolution.PassGuardServerApplication.credentialModule, IdentitySolution.Database, "", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
@enduml