@startuml
set separator none
title Identity Service - System Context

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>

AddBoundaryTag("3rd Party System", $borderColor="#cccccc", $fontColor="#cccccc", $borderStyle="Dashed", $borderThickness="1")
Boundary(group_1, "3rd Party System", $tags="3rd Party System") {
  System(3rdPartyApplication, "3rd-Party Application", $descr="A system to use Barracks as a identity provider", $tags="", $link="")
}

AddBoundaryTag("Barracks", $borderColor="#cccccc", $fontColor="#cccccc", $borderStyle="Dashed", $borderThickness="1")
Boundary(group_2, "Barracks", $tags="Barracks") {
  System(IdentityService, "Identity Service", $descr="Identity Solution Provider.", $tags="", $link="")
}


Rel(3rdPartyApplication, IdentityService, "", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
@enduml