@startuml
set separator none
title System Landscape

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>

AddBoundaryTag("PassGuard", $borderColor="#cccccc", $fontColor="#cccccc", $borderStyle="Dashed", $borderThickness="1")
Boundary(group_1, "PassGuard", $tags="PassGuard") {
  System(PassGuardIdentity, "PassGuard Identity", $descr="", $tags="", $link="")
}

AddBoundaryTag("Users", $borderColor="#cccccc", $fontColor="#cccccc", $borderStyle="Dashed", $borderThickness="1")
Boundary(group_2, "Users", $tags="Users") {
  Person(WebServiceUser, "WebServiceUser", $descr="web service user", $tags="", $link="")
}

AddBoundaryTag("WebService", $borderColor="#cccccc", $fontColor="#cccccc", $borderStyle="Dashed", $borderThickness="1")
Boundary(group_3, "WebService", $tags="WebService") {
  Person(WebServiceDeveloper, "WebServiceDeveloper", $descr="web service developer", $tags="", $link="")
  System(WebService, "Web Service", $descr="web service requiring login system", $tags="", $link="")
}


Rel(WebServiceUser, PassGuardIdentity, "", $techn="", $tags="", $link="")
Rel(WebService, PassGuardIdentity, "", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
@enduml