@startuml
set separator none
title PassGuard Server Application - Dynamic

left to right direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Container>
!include <C4/C4_Component>

Container_Boundary("IdentityService.PassGuardServerApplication_boundary", "PassGuard Server Application", $tags="") {
  Component(IdentityService.PassGuardServerApplication.PassGuardServer, "PassGuard Server", $techn="NextJS Server Application", $descr="Verifier", $tags="", $link="")
}

Container_Boundary("IdentityService.Database_boundary", "Database", $tags="") {
  Component(IdentityService.Database.userDataModel, "userDataModel", $techn="", $descr="User Data Model", $tags="", $link="")
  Component(IdentityService.Database.credentialDataModel, "credentialDataModel", $techn="", $descr="Credential Data Model", $tags="", $link="")
}

Container(IdentityService.LoginWebApplication, "Login Web Application", $techn="NextJS", $descr="Authenticator(Client Device)", $tags="", $link="")

Rel(IdentityService.LoginWebApplication, IdentityService.PassGuardServerApplication.PassGuardServer, "1. request 3rd party service registration", $techn="", $tags="", $link="")
Rel(IdentityService.PassGuardServerApplication.PassGuardServer, IdentityService.Database.credentialDataModel, "2. check out the 3rd party service and the user info", $techn="", $tags="", $link="")
Rel(IdentityService.PassGuardServerApplication.PassGuardServer, IdentityService.PassGuardServerApplication.PassGuardServer, "3. process validate the service and user duplication", $techn="", $tags="", $link="")
Rel(IdentityService.PassGuardServerApplication.PassGuardServer, IdentityService.Database.userDataModel, "4. create user info associated with the service", $techn="", $tags="", $link="")
Rel(IdentityService.LoginWebApplication, IdentityService.LoginWebApplication, "5. issue credential", $techn="", $tags="", $link="")
Rel(IdentityService.LoginWebApplication, IdentityService.PassGuardServerApplication.PassGuardServer, "6. request credential registration", $techn="", $tags="", $link="")
Rel(IdentityService.PassGuardServerApplication.PassGuardServer, IdentityService.PassGuardServerApplication.PassGuardServer, "7. process validate the credential", $techn="", $tags="", $link="")
Rel(IdentityService.PassGuardServerApplication.PassGuardServer, IdentityService.Database.credentialDataModel, "8. update", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
@enduml